AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WebSocket Chat with TypeScript + esbuild

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs20.x
    Architectures:
      - x86_64

Resources:

  #################################
  # DynamoDB Table
  #################################
  ChatConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ChatConnections
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: groupId
          AttributeType: S
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: groupId
          KeyType: HASH
        - AttributeName: connectionId
          KeyType: RANGE

  #################################
  # WebSocket API
  #################################
  ChatWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ChatWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  #################################
  # Lambda Function
  #################################
  ChatLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ChatConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatConnectionsTable
        - Statement:
            - Effect: Allow
              Action:
                - execute-api:ManageConnections
              Resource:
                - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ChatWebSocketApi}/*

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: es2020
        Minify: false
        Sourcemap: false
        EntryPoints:
          - handler.ts

  #################################
  # Lambda Permission
  #################################
  ChatLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ChatLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ChatWebSocketApi}/*

  #################################
  # API Integration
  #################################
  ChatLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ChatLambdaFunction.Arn}/invocations

  #################################
  # Routes
  #################################
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Join [ "/", [ "integrations", !Ref ChatLambdaIntegration ] ]

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $disconnect
      Target: !Join [ "/", [ "integrations", !Ref ChatLambdaIntegration ] ]

  SendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: sendMessage
      Target: !Join [ "/", [ "integrations", !Ref ChatLambdaIntegration ] ]

  #################################
  # Deployment & Stage
  #################################
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - SendRoute
    Properties:
      ApiId: !Ref ChatWebSocketApi

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: prod
      DeploymentId: !Ref Deployment
      ApiId: !Ref ChatWebSocketApi

#################################
# Outputs
#################################
Outputs:
  WebSocketURL:
    Description: WebSocket URL
    Value: !Sub wss://${ChatWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/prod

  TableName:
    Description: DynamoDB Table Name
    Value: !Ref ChatConnectionsTable

  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref ChatLambdaFunction